Repository DevCourse-KACG/Frontend, pull requests merged in 2025-08, with the labels that each got.

#38 [Feat] 내 정보
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/members.ts
  frontend/src/app/login/page.tsx
  frontend/src/app/members/login/page.tsx
  frontend/src/app/members/mypage/page.tsx
  frontend/src/app/members/register/page.tsx
  frontend/src/lib/api.ts
Labels: feat

#40 [Feat] 일정 상세화면, 일정 삭제
  frontend/src/api/schedule.ts
  frontend/src/app/schedule/modals/ScheduleModal.tsx
  frontend/src/app/schedule/page.tsx
  frontend/src/components/domain/schedule/Calender.tsx
  frontend/src/types/schedule.ts
Labels: feat

#41 [Feat] 내 정보 수정
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/members.ts
  frontend/src/app/members/mypage/edit-profile/page.tsx
  frontend/src/app/members/mypage/page.tsx
  frontend/src/app/members/mypage/verify-password/page.tsx
  frontend/src/app/members/register/page.tsx
Labels: feat

#43 [Feat] 일정 생성, 수정 모달
  frontend/src/app/schedule/modals/ScheduleEditModal.tsx
  frontend/src/app/schedule/modals/ScheduleModal.tsx
  frontend/src/app/schedule/page.tsx
  frontend/src/components/domain/schedule/Calender.tsx
  frontend/src/types/schedule.ts
Labels: feat

#45 [Feat] 내 일정 목록
  frontend/src/api/schedule.ts
  frontend/src/app/schedule/modals/ScheduleModal.tsx
  frontend/src/app/schedule/my/page.tsx
  frontend/src/app/schedule/page.tsx
  frontend/src/components/domain/schedule/Calender.tsx
  frontend/src/constants/colors.tsx
  frontend/src/hooks/useSchedules.ts
  frontend/src/lib/fullcalendar.css
Labels: feat

#51 [Feat] 비회원용 모임 가입
  frontend/src/api/members.ts
  frontend/src/app/clubs/invite/page.tsx
  frontend/src/app/members/guest-register/page.tsx
Labels: feat

#49 [design] 모임 수정 페이지 구성
  frontend/src/api/club.tsx
  frontend/src/app/clubs/[clubId]/page.tsx
  frontend/src/app/clubs/[clubId]/settings/delete/page.tsx
  frontend/src/app/clubs/[clubId]/settings/edit/page.tsx
  frontend/src/app/clubs/new/page.tsx
  frontend/src/components/domain/clubs/clubDataForm.tsx
  frontend/src/components/domain/clubs/settingButton.tsx
Labels: design

#53 [Feat] 메인 페이지
  frontend/src/app/page.tsx
Labels: feat

#57 [Feat] 친구 목록 화면
  frontend/src/api/friend.ts
  frontend/src/app/members/friend/page.tsx
  frontend/src/components/domain/friend/FriendsAccordion.tsx
  frontend/src/components/domain/friend/FriendsItem.tsx
  frontend/src/lib/avatarUtils.ts
  frontend/src/types/backend/apiV1/schema.d.ts
  frontend/src/types/friend.ts
Labels: feat

#61 [design] 클럽 관련 디자인 다듬기
  frontend/src/app/clubs/[clubId]/members/page.tsx
  frontend/src/app/clubs/[clubId]/page.tsx
  frontend/src/app/clubs/public/page.tsx
  frontend/src/components/domain/clubs/clubCard.tsx
  frontend/src/components/domain/clubs/clubInfo.tsx
  frontend/src/components/domain/clubs/clubInfoSideMenu.tsx
  frontend/src/components/domain/clubs/clubIntroInfo.tsx
  frontend/src/components/global/InfoCard.tsx
Labels: design

#66 [Refactor] 메인, 마이페이지 ui 수정
  frontend/next.config.ts
  frontend/public/create-club-image.jpg
  frontend/src/api/members.ts
  frontend/src/app/globals.css
  frontend/src/app/members/mypage/page.tsx
  frontend/src/app/members/mypage/verify-password/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/global/footer.tsx
  frontend/src/components/global/header.tsx
Labels: refactor

#68 [fix] 일정에서 클럽 id 숫자 처리
  frontend/src/app/schedule/page.tsx
Labels: fix

#69 [hotfix] env 환경 변수 변경
  frontend/src/api/club.tsx
  frontend/src/api/clubLink.ts
  frontend/src/api/clubMember.tsx
  frontend/src/api/myClub.tsx
  frontend/src/app/members/mypage/edit-profile/page.tsx
  frontend/src/app/test/[clubId]/page.tsx
Labels: fix

#74 [Refactor] 체크리스트 groupId clubId로 변경
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/checklists/[checklistId]/page.tsx
  frontend/src/app/checklists/create/page.tsx
  frontend/src/app/checklists/page.tsx
  frontend/src/components/domain/clubs/clubInfoSideMenu.tsx
Labels: refactor

#84 [refactor] 체크리스트 버튼 주석해제
  frontend/src/app/schedule/modals/ScheduleModal.tsx
Labels: refactor

#81 Feat 초대링크
  frontend/src/app/clubs/[clubId]/settings/invite/page.tsx
Labels: feat

#87 [refactor] 체크리스트 생성 url 변경
  frontend/src/app/schedule/page.tsx
Labels: refactor
